base_url = "https://bd103.github.io"
title = "BD103's Blog"
# description = "xxxx xxxx xxxx"
default_language = "en"
theme = "serene"
# Keep this false, as it may cause issues with some styles
minify_html = false
# Search is temporarily unsupported
build_search_index = false
generate_feeds = true
feed_filenames = ["feed.xml", "atom.xml"]
taxonomies = [
  { name = "tags" },
  { name = "categories" },
]

[markdown]
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["themes/serene/highlight_themes"]
highlight_themes_css = [
  { theme = "serene-light", filename = "hl-light.css" },
  { theme = "serene-dark", filename = "hl-dark.css" },
]
render_emoji = false
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
sections = [
  { name = "Posts", path = "/blog", is_external = false },
  # { name = "tags", path = "/tags", is_external = false },
  # { name = "github", path = "https://github.com/BD103", is_external = true },
]
blog_section_path = "/blog"

back_link_text = "Backtrack"
force_theme = false

footer_copyright = "©2025 BD103"
# Give credit to Serene and Zola
footer_credits = true

not_found_error_text = "404 Not Found"
not_found_recover_text = "« back to home »"
