base_url = "https://bd103.dev"
title = "BD103's Blog"
description = "Technical writing on Bevy, Rust, and more"
default_language = "en"
theme = "serene"
# Generate Atom feed.
generate_feeds = true
feed_filenames = ["feed.xml", "atom.xml"]
author = "BD103"
taxonomies = [
  { name = "tags" },
]

[markdown]
github_alerts = true
bottom_footnotes = true

[markdown.highlighting]
style = "class"
light_theme = "catppuccin-latte"
dark_theme = "catppuccin-mocha"

[slugify]
paths_keep_dates = true

[extra]
name = "BD103"
handle = "bd103"
bio = "Rust enthusiast and Bevy contributor"
avatar = "img/avatar.png"
links = [
  { name = "GitHub", icon = "github", url = "https://github.com/BD103" },
  { name = "Mastodon", icon = "mastodon", url = "https://hachyderm.io/@bd103", rel_me = true },
]

nav = [
  { name = "Posts", path = "/blog" },
  { name = "Tags", path = "/tags" },
  { name = "Source", path = "https://github.com/BD103/bd103.github.io" },
  { name = "RSS", path = "/feed.xml" },
]
blog_section_path = "/blog"

back_link_text = "Return"
color_scheme = "auto"

footer_copyright = "©2026 BD103"
# Give credit to Serene and Zola.
footer_credits = true

not_found_error_text = "404 Not Found :("
not_found_recover_text = "$ cd ~"

# Emoji reactions are not setup.
reaction = false
