name: Deploy

on:
  # Update on pushes to main
  push:
    branches: [main]

  # Allow running workflow manually
  workflow_dispatch:

# Only run one at a time, but don't cancel in-progress deployments
concurrency:
  group: pages
  cancel-in-progress: false

permissions: {}

jobs:
  # Build the site and publish an artifact
  build:
    runs-on: ubuntu-slim
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true
          persist-credentials: false

      - name: Install Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.22

      - name: Build site
        run: zola build

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: public

  # Download build's artifact and publish site
  deploy:
    runs-on: ubuntu-slim
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # These permissions are required to deploy to Github Pages.
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v5
