name: Deploy

on:
  # Update on pushes to main
  push:
    branches: ["main"]

  # Allow running workflow manually
  workflow_dispatch:

# Restrict permissions to just Github Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Only run one at a time, but don't cancel in-progress deployments
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build the site and publish an artifact
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"
      
      - name: Build site
        run: |
          pnpm install
          pnpm generate
      
      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ".output/public"

  # Download build's artifact and publish site
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v2
